[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

# Allow writing deployment.json
fs_permissions = [{ access = "read-write", path = "./" }]

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "automata-dcap-attestation/=lib/automata-dcap-attestation/evm/contracts/",
]
